name: widgetbook_generator
description: A package to automate setup and maintanance of the widgetbook package by using code generation.
version: 3.0.0-rc.2
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_generator
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io/widgetbook-generator/overview
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ^5.10.0
  build: ^2.1.0
  collection: ^1.15.0
  glob: ^2.0.2
  json_annotation: ^4.8.0
  meta: ^1.7.0
  source_gen: ^1.1.0
  widgetbook_annotation:
    path: ./../widgetbook_annotation
    # git: 
    #   url: https://github.com/mikepattyn/widgetbook.git
    #   path: packages/widgetbook_annotation

dev_dependencies:
  test: ^1.24.1
